-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 10:44:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_click_solucoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_click_solucoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_click_solucoes` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `db_click_solucoes` ;

-- -----------------------------------------------------
-- Table `db_click_solucoes`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_click_solucoes`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipoServico` VARCHAR(255) NOT NULL,
  `profissao` VARCHAR(255) NOT NULL,
  `contratacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_click_solucoes`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_click_solucoes`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `datadenascimento` DATE NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `cnpj` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_click_solucoes`.`tb_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_click_solucoes`.`tb_servicos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `local` VARCHAR(255) NOT NULL,
  `valor` DECIMAL NULL,
  `foto` VARCHAR(255) NULL,
  `tb_categorias_id` BIGINT NULL,
  `tb_usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_servicos_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  INDEX `fk_tb_servicos_tb_usuario1_idx` (`tb_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_servicos_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_click_solucoes`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_servicos_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_click_solucoes`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
